### ISSUE TITLE
Can't compile Xcode 9 - NSError 

### ISSUE THREAD

**Issue by sardon** [saasquatch/mobile-sdk-swift-cocoapod#1]
This pod doesn't compile on Xcode 9.2, swift 4. 

6 instances of the same error are reported: 
```
saasquatch-sdk-swift/saasquatch/classes/Saasquatch.swift:107:104: error: cannot convert value of type '[AnyHashable : Any]' to expected argument type '[String : Any]?'
                let error = NSError(domain: "HTTP error", code: (httpResponse?.statusCode)!, userInfo: userInfo)
```

**Comment by mreams** [comment]
Thanks for giving us the exact error message! Sorry about the delay, I'm working on that right now.

**Comment by mreams** [comment]
Version 2.0.0 for Swift 4 is out! Please let us know if you have any problems with the new version, we'll be much more responsive now that we're all back in the office.

**Comment by loganvolkers** [comment]
@sardon Could you help us out and confirm that Version 2 fixes your Swift 4 problem?

**Comment by sardon** [comment]
Yes, fixed thanks

/sebastien
